### PR TITLE
Use newer "ReadPassword" and fall back to visible readline.

### LINKED ISSUE #336: reading passwords on git-bash fails
The terminal does a `MakeRaw` which seems to fail with "The handle is invalid".
https://groups.google.com/g/golang-nuts/c/qW78_nLy79c

The fix seems to be to use a more recent package:
https://stackoverflow.com/a/65852707/997251

### PR DESCRIPTION
**Pull request by floitsch**
On Windows, in git-bash (and similar shells) the 'ReadPassword' function has difficulties.

See https://github.com/golang/go/issues/11914#issuecomment-613715787.

Fixes #336.

### CODE REVIEW

File: cmd/jag/commands/util.go [hunk 1]
```diff
@@ -536,12 +511,21 @@ func getWifiCredentials(cmd *cobra.Command) (string, string, error) {
 		wifiPassword = cfg.GetString(WifiCfgKey + "." + WifiPasswordCfgKey)
 	} else {
 		fmt.Printf("Enter WiFi password for '%s': ", wifiSSID)
-		pw, err := ReadPassword()
-		if err != nil {
+		pw := ""
+		pw_bytes, err := ReadPassword()
```
Comment (kasperl) [inline cmd/jag/commands/util.go:515]:
```suggestion
		pwBytes, err := ReadPassword()
```

File: cmd/jag/commands/util.go [hunk 2]
```diff
@@ -536,12 +511,21 @@ func getWifiCredentials(cmd *cobra.Command) (string, string, error) {
...
+		if err == nil {
+			pw = string(pw_bytes)
```
Comment (kasperl) [inline cmd/jag/commands/util.go:517]:
```suggestion
			pw = string(pwBytes)
```

**Review by kasperl — APPROVED** [review]
Looks good to me.
