### PR TITLE
Fix crash and provide better error when chip is wrong.

### LINKED ISSUE #558: Crash when an envelope can't be found
I have an ESP32-S3 chipset. I am trying to install jaguar on the chipset but failing with the following error. 

```
❯ jag flash -p /dev/ttyACM1 -c ESP32-S3

Downloading ESP32-S3 firmware from https://github.com/toitlang/envelopes/releases/download/v2.0.0-alpha.160/firmware-ESP32-S3.envelope.gz ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb2e6a8]

goroutine 1 [running]:
github.com/toitlang/jaguar/cmd/jag/commands.downloadGzipped({0xe089d8?, 0xc000199c50?}, {0xc000042a10?, 0xccf6a2?}, {0xc00007f3e0, 0x52})
	/home/runner/work/jaguar/jaguar/cmd/jag/commands/envelope.go:44 +0x48
github.com/toitlang/jaguar/cmd/jag/commands.downloadPublishedFirmware({0xe089d8, 0xc000199c50}, {0xc000040cc0, 0x10}, {0x7ffe28ed88b5, 0x8})
	/home/runner/work/jaguar/jaguar/cmd/jag/commands/envelope.go:136 +0x2ad
github.com/toitlang/jaguar/cmd/jag/commands.GetCachedFirmwareEnvelopePath({0xe089d8, 0xc000199c50}, {0xc000040cc0, 0x10}, {0x7ffe28ed88b5, 0x8})
	/home/runner/work/jaguar/jaguar/cmd/jag/commands/envelope.go:27 +0x105
github.com/toitlang/jaguar/cmd/jag/commands.FlashCmd.func1(0xc0001ecf08, {0xc0001ce840, 0x0, 0xccf6d2?})
	/home/runner/work/jaguar/jaguar/cmd/jag/commands/flash.go:97 +0x6e5
github.com/spf13/cobra.(*Command).execute(0xc0001ecf08, {0xc0001ce800, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001e2608)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(0xcd1106?, {0xe089d8?, 0xc000199c50?})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1032 +0x47
main.main()
	/home/runner/work/jaguar/jaguar/cmd/jag/main.go:34 +0x18b
```

### PR DESCRIPTION
**Pull request by floitsch**
Fixes #558

### CODE REVIEW

File: cmd/jag/commands/envelope.go [hunk 1]
```diff
@@ -41,11 +53,10 @@ func isURL(path string) bool {
 
 func downloadGzipped(ctx context.Context, url string, path string) error {
 	bundle, err := download(ctx, url)
-	defer bundle.Close()
 	if err != nil {
 		return err
 	}
-
+	defer bundle.Close()
```
Comment (yudistrange) [inline cmd/jag/commands/envelope.go:59]: Uh.. this seems unrelated, right?

Also (I'm not an expert at golang so please correct me) can deferring after the `err != nil check` lead to bundle not being closed because in case of an error the program will return before the defer is set?

Comment (kasperl) [reply cmd/jag/commands/envelope.go:59]: The thinking is that if `err == nil`, then `bundle` will be nil or at least not open. If `bundle` is nil, then calling `bundle.Close` (even deferred) will cause a crash.

**Review by kasperl — APPROVED** [review]
Looks good to me.
